config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # get 'welcome/index'
  # root 'welcome#index'

  resources :adresses
  resources :roles
  resources :paying_methods
  resources :orders
  resources :sauces
  resources :veggies
  resources :mains
  resources :breads
  resources :hoagies
  resources :ingredients
  resources :users
  resources :user1s
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adress.rb
# frozen_string_literal: true

class Adress < ApplicationRecord
end

app/models/bread.rb
# frozen_string_literal: true

class Bread < ApplicationRecord
end

app/models/hoagie.rb
# frozen_string_literal: true

class Hoagie < ApplicationRecord
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
end

app/models/main.rb
# frozen_string_literal: true

class Main < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/paying_method.rb
# frozen_string_literal: true

class PayingMethod < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
end

app/models/sauce.rb
# frozen_string_literal: true

class Sauce < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include FactoryBot::Syntax::Methods
  validates_presence_of :userID
  validates_presence_of :surName
  validates_presence_of :name 
end

app/models/user1.rb
# frozen_string_literal: true

class User1 < ApplicationRecord
end

app/models/veggie.rb
# frozen_string_literal: true

class Veggie < ApplicationRecord
end

app/controllers/paying_methods_controller.rb
# frozen_string_literal: true

class PayingMethodsController < ApplicationController
  before_action :set_paying_method, only: %i[show edit update destroy]

  # GET /paying_methods
  # GET /paying_methods.json
  def index
    @paying_methods = PayingMethod.all
  end

  # GET /paying_methods/1
  # GET /paying_methods/1.json
  def show; end

  # GET /paying_methods/new
  def new
    @paying_method = PayingMethod.new
  end

  # GET /paying_methods/1/edit
  def edit; end

  # POST /paying_methods
  # POST /paying_methods.json
  def create
    @paying_method = PayingMethod.new(paying_method_params)

    respond_to do |format|
      if @paying_method.save
        format.html { redirect_to @paying_method, notice: 'Paying method was successfully created.' }
        format.json { render :show, status: :created, location: @paying_method }
      else
        format.html { render :new }
        format.json { render json: @paying_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paying_methods/1
  # PATCH/PUT /paying_methods/1.json
  def update
    respond_to do |format|
      if @paying_method.update(paying_method_params)
        format.html { redirect_to @paying_method, notice: 'Paying method was successfully updated.' }
        format.json { render :show, status: :ok, location: @paying_method }
      else
        format.html { render :edit }
        format.json { render json: @paying_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paying_methods/1
  # DELETE /paying_methods/1.json
  def destroy
    @paying_method.destroy
    respond_to do |format|
      format.html { redirect_to paying_methods_url, notice: 'Paying method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_paying_method
    @paying_method = PayingMethod.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def paying_method_params
    params.require(:paying_method).permit(:provider)
  end
end

app/helpers/breads_helper.rb
# frozen_string_literal: true

module BreadsHelper
end

app/helpers/hoagies_helper.rb
# frozen_string_literal: true

module HoagiesHelper
end

app/helpers/mains_helper.rb
# frozen_string_literal: true

module MainsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/paying_methods_helper.rb
# frozen_string_literal: true

module PayingMethodsHelper
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/helpers/sauces_helper.rb
# frozen_string_literal: true

module SaucesHelper
end

app/helpers/user1s_helper.rb
# frozen_string_literal: true

module User1sHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/paying_methods/_form.html.erb
<%= form_with(model: paying_method, local: true) do |form| %>
  <% if paying_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paying_method.errors.count, "error") %> prohibited this paying_method from being saved:</h2>

      <ul>
      <% paying_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :provider %>
    <%= form.text_field :provider %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paying_methods/edit.html.erb
<h1>Editing Paying Method</h1>

<%= render 'form', paying_method: @paying_method %>

<%= link_to 'Show', @paying_method %> |
<%= link_to 'Back', paying_methods_path %>

app/views/paying_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paying Methods</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paying_methods.each do |paying_method| %>
      <tr>
        <td><%= paying_method.provider %></td>
        <td><%= link_to 'Show', paying_method %></td>
        <td><%= link_to 'Edit', edit_paying_method_path(paying_method) %></td>
        <td><%= link_to 'Destroy', paying_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paying Method', new_paying_method_path %>

app/views/paying_methods/new.html.erb
<h1>New Paying Method</h1>

<%= render 'form', paying_method: @paying_method %>

<%= link_to 'Back', paying_methods_path %>

app/views/paying_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @paying_method.provider %>
</p>

<%= link_to 'Edit', edit_paying_method_path(@paying_method) %> |
<%= link_to 'Back', paying_methods_path %>