config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # get 'welcome/index'
  # root 'welcome#index'

  resources :adresses
  resources :roles
  resources :paying_methods
  resources :orders
  resources :sauces
  resources :veggies
  resources :mains
  resources :breads
  resources :hoagies
  resources :ingredients
  resources :users
  resources :user1s
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adress.rb
# frozen_string_literal: true

class Adress < ApplicationRecord
end

app/models/bread.rb
# frozen_string_literal: true

class Bread < ApplicationRecord
end

app/models/hoagie.rb
# frozen_string_literal: true

class Hoagie < ApplicationRecord
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
end

app/models/main.rb
# frozen_string_literal: true

class Main < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/paying_method.rb
# frozen_string_literal: true

class PayingMethod < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
end

app/models/sauce.rb
# frozen_string_literal: true

class Sauce < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include FactoryBot::Syntax::Methods
  validates_presence_of :userID
  validates_presence_of :surName
  validates_presence_of :name 
end

app/models/user1.rb
# frozen_string_literal: true

class User1 < ApplicationRecord
end

app/models/veggie.rb
# frozen_string_literal: true

class Veggie < ApplicationRecord
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[show edit update destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show; end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit; end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ingredient_params
    params.require(:ingredient).permit(:IDIngred, :name, :description, :price, :type)
  end
end

app/helpers/breads_helper.rb
# frozen_string_literal: true

module BreadsHelper
end

app/helpers/hoagies_helper.rb
# frozen_string_literal: true

module HoagiesHelper
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/helpers/mains_helper.rb
# frozen_string_literal: true

module MainsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/helpers/sauces_helper.rb
# frozen_string_literal: true

module SaucesHelper
end

app/helpers/user1s_helper.rb
# frozen_string_literal: true

module User1sHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :IDIngred %>
    <%= form.text_field :IDIngred %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Idingred</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.IDIngred %></td>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.description %></td>
        <td><%= ingredient.price %></td>
        <td><%= ingredient.type %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idingred:</strong>
  <%= @ingredient.IDIngred %>
</p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ingredient.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ingredient.price %>
</p>

<p>
  <strong>Type:</strong>
  <%= @ingredient.type %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>