config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # get 'welcome/index'
  # root 'welcome#index'

  resources :adresses
  resources :roles
  resources :paying_methods
  resources :orders
  resources :sauces
  resources :veggies
  resources :mains
  resources :breads
  resources :hoagies
  resources :ingredients
  resources :users
  resources :user1s
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adress.rb
# frozen_string_literal: true

class Adress < ApplicationRecord
end

app/models/bread.rb
# frozen_string_literal: true

class Bread < ApplicationRecord
end

app/models/hoagie.rb
# frozen_string_literal: true

class Hoagie < ApplicationRecord
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
end

app/models/main.rb
# frozen_string_literal: true

class Main < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/paying_method.rb
# frozen_string_literal: true

class PayingMethod < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
end

app/models/sauce.rb
# frozen_string_literal: true

class Sauce < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include FactoryBot::Syntax::Methods
  validates_presence_of :userID
  validates_presence_of :surName
  validates_presence_of :name 
end

app/models/user1.rb
# frozen_string_literal: true

class User1 < ApplicationRecord
end

app/models/veggie.rb
# frozen_string_literal: true

class Veggie < ApplicationRecord
end

app/controllers/veggies_controller.rb
# frozen_string_literal: true

class VeggiesController < ApplicationController
  before_action :set_veggy, only: %i[show edit update destroy]

  # GET /veggies
  # GET /veggies.json
  def index
    @veggies = Veggie.all
  end

  # GET /veggies/1
  # GET /veggies/1.json
  def show; end

  # GET /veggies/new
  def new
    @veggy = Veggie.new
  end

  # GET /veggies/1/edit
  def edit; end

  # POST /veggies
  # POST /veggies.json
  def create
    @veggy = Veggie.new(veggy_params)

    respond_to do |format|
      if @veggy.save
        format.html { redirect_to @veggy, notice: 'Veggie was successfully created.' }
        format.json { render :show, status: :created, location: @veggy }
      else
        format.html { render :new }
        format.json { render json: @veggy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veggies/1
  # PATCH/PUT /veggies/1.json
  def update
    respond_to do |format|
      if @veggy.update(veggy_params)
        format.html { redirect_to @veggy, notice: 'Veggie was successfully updated.' }
        format.json { render :show, status: :ok, location: @veggy }
      else
        format.html { render :edit }
        format.json { render json: @veggy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veggies/1
  # DELETE /veggies/1.json
  def destroy
    @veggy.destroy
    respond_to do |format|
      format.html { redirect_to veggies_url, notice: 'Veggie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_veggy
    @veggy = Veggie.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def veggy_params
    params.require(:veggy).permit(:vID, :vName)
  end
end

app/helpers/breads_helper.rb
# frozen_string_literal: true

module BreadsHelper
end

app/helpers/mains_helper.rb
# frozen_string_literal: true

module MainsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/helpers/sauces_helper.rb
# frozen_string_literal: true

module SaucesHelper
end

app/helpers/user1s_helper.rb
# frozen_string_literal: true

module User1sHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/veggies_helper.rb
# frozen_string_literal: true

module VeggiesHelper
end

app/views/veggies/_form.html.erb
<%= form_with(model: veggy, local: true) do |form| %>
  <% if veggy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(veggy.errors.count, "error") %> prohibited this veggy from being saved:</h2>

      <ul>
      <% veggy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vID %>
    <%= form.text_field :vID %>
  </div>

  <div class="field">
    <%= form.label :vName %>
    <%= form.text_field :vName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/veggies/edit.html.erb
<h1>Editing Veggy</h1>

<%= render 'form', veggy: @veggy %>

<%= link_to 'Show', @veggy %> |
<%= link_to 'Back', veggies_path %>

app/views/veggies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Veggies</h1>

<table>
  <thead>
    <tr>
      <th>Vid</th>
      <th>Vname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veggies.each do |veggy| %>
      <tr>
        <td><%= veggy.vID %></td>
        <td><%= veggy.vName %></td>
        <td><%= link_to 'Show', veggy %></td>
        <td><%= link_to 'Edit', edit_veggy_path(veggy) %></td>
        <td><%= link_to 'Destroy', veggy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veggy', new_veggy_path %>

app/views/veggies/new.html.erb
<h1>New Veggy</h1>

<%= render 'form', veggy: @veggy %>

<%= link_to 'Back', veggies_path %>

app/views/veggies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vid:</strong>
  <%= @veggy.vID %>
</p>

<p>
  <strong>Vname:</strong>
  <%= @veggy.vName %>
</p>

<%= link_to 'Edit', edit_veggy_path(@veggy) %> |
<%= link_to 'Back', veggies_path %>