config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # get 'welcome/index'
  # root 'welcome#index'

  resources :adresses
  resources :roles
  resources :paying_methods
  resources :orders
  resources :sauces
  resources :veggies
  resources :mains
  resources :breads
  resources :hoagies
  resources :ingredients
  resources :users
  resources :user1s
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adress.rb
# frozen_string_literal: true

class Adress < ApplicationRecord
end

app/models/bread.rb
# frozen_string_literal: true

class Bread < ApplicationRecord
end

app/models/hoagie.rb
# frozen_string_literal: true

class Hoagie < ApplicationRecord
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
end

app/models/main.rb
# frozen_string_literal: true

class Main < ApplicationRecord
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
end

app/models/paying_method.rb
# frozen_string_literal: true

class PayingMethod < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
end

app/models/sauce.rb
# frozen_string_literal: true

class Sauce < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include FactoryBot::Syntax::Methods
  validates_presence_of :userID
  validates_presence_of :surName
  validates_presence_of :name 
end

app/models/user1.rb
# frozen_string_literal: true

class User1 < ApplicationRecord
end

app/models/veggie.rb
# frozen_string_literal: true

class Veggie < ApplicationRecord
end

app/controllers/sauces_controller.rb
# frozen_string_literal: true

class SaucesController < ApplicationController
  before_action :set_sauce, only: %i[show edit update destroy]

  # GET /sauces
  # GET /sauces.json
  def index
    @sauces = Sauce.all
  end

  # GET /sauces/1
  # GET /sauces/1.json
  def show; end

  # GET /sauces/new
  def new
    @sauce = Sauce.new
  end

  # GET /sauces/1/edit
  def edit; end

  # POST /sauces
  # POST /sauces.json
  def create
    @sauce = Sauce.new(sauce_params)

    respond_to do |format|
      if @sauce.save
        format.html { redirect_to @sauce, notice: 'Sauce was successfully created.' }
        format.json { render :show, status: :created, location: @sauce }
      else
        format.html { render :new }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sauces/1
  # PATCH/PUT /sauces/1.json
  def update
    respond_to do |format|
      if @sauce.update(sauce_params)
        format.html { redirect_to @sauce, notice: 'Sauce was successfully updated.' }
        format.json { render :show, status: :ok, location: @sauce }
      else
        format.html { render :edit }
        format.json { render json: @sauce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sauces/1
  # DELETE /sauces/1.json
  def destroy
    @sauce.destroy
    respond_to do |format|
      format.html { redirect_to sauces_url, notice: 'Sauce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sauce
    @sauce = Sauce.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sauce_params
    params.require(:sauce).permit(:sID, :sName)
  end
end

app/helpers/breads_helper.rb
# frozen_string_literal: true

module BreadsHelper
end

app/helpers/hoagies_helper.rb
# frozen_string_literal: true

module HoagiesHelper
end

app/helpers/mains_helper.rb
# frozen_string_literal: true

module MainsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

module RolesHelper
end

app/helpers/sauces_helper.rb
# frozen_string_literal: true

module SaucesHelper
end

app/helpers/user1s_helper.rb
# frozen_string_literal: true

module User1sHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/veggies_helper.rb
# frozen_string_literal: true

module VeggiesHelper
end

app/views/sauces/_form.html.erb
<%= form_with(model: sauce, local: true) do |form| %>
  <% if sauce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sauce.errors.count, "error") %> prohibited this sauce from being saved:</h2>

      <ul>
      <% sauce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sID %>
    <%= form.text_field :sID %>
  </div>

  <div class="field">
    <%= form.label :sName %>
    <%= form.text_field :sName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sauces/edit.html.erb
<h1>Editing Sauce</h1>

<%= render 'form', sauce: @sauce %>

<%= link_to 'Show', @sauce %> |
<%= link_to 'Back', sauces_path %>

app/views/sauces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sauces</h1>

<table>
  <thead>
    <tr>
      <th>Sid</th>
      <th>Sname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sauces.each do |sauce| %>
      <tr>
        <td><%= sauce.sID %></td>
        <td><%= sauce.sName %></td>
        <td><%= link_to 'Show', sauce %></td>
        <td><%= link_to 'Edit', edit_sauce_path(sauce) %></td>
        <td><%= link_to 'Destroy', sauce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sauce', new_sauce_path %>

app/views/sauces/new.html.erb
<h1>New Sauce</h1>

<%= render 'form', sauce: @sauce %>

<%= link_to 'Back', sauces_path %>

app/views/sauces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sid:</strong>
  <%= @sauce.sID %>
</p>

<p>
  <strong>Sname:</strong>
  <%= @sauce.sName %>
</p>

<%= link_to 'Edit', edit_sauce_path(@sauce) %> |
<%= link_to 'Back', sauces_path %>